modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/tbhmens/privtell"
[[mods]]
modId="privtell"
version="${file.jarVersion}"
displayName="PrivTell"
#updateJSONURL="http://.../"
displayURL="https://github.com/tbhmens/privtell"
#logoFile="....png"
#credits="..."
authors="tbhmens"
description='''
/tell, but private and encrypted.
'''