name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Gradle
        run: sh ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: PrivTell
          path: build/libs/*.jar
